### PR TITLE
Update README.md with correct spelling

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
This PR is linked to the issue I created. It fixes the spelling of programme to program.

### CODE REVIEW

**Comment by CodeMaster7000** [comment]
@SmashedFrenzy16 Program is a valid spelling in all versions of English apart from British English (e.g. Canadian, American, Australian). Therefore foreign users will not see an issue with this.

**Review by ShashCode2348 — APPROVED** [review]

**Comment by ShashCode2348** [comment]
Conflicts with original after edits, will still take the advice though

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000, still, I feel that this change should be made.

**Comment by CodeMaster7000** [comment]
@SmashedFrenzy16 After all, it is a minor change and a debatable concept. You could consider fixing up a different README. Not to mention, he has approved your changes and might incorporate them into the README anyways :)

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000 i did not mean it like that. I know he approved my changes but I just found it better if it was program.

**Comment by SmashedFrenzy16** [comment]
But I understand what you are saying as well.

**Pull request closed without merging**
